### ISSUE TITLE
`footer`をつけようかな〜〜〜？

### ISSUE THREAD

**Issue by ShionTerunaga** [ShionTerunaga/new-site-2024#25]
# 内容

サイトにfooterをつけるかどうかの相談・つけるなら実装まで行う

# 詳細

- footerつけたいなと思うんだけどどうだか
- デザインの相談(SNSのリンク等は載せるべきか？)
- copyright欲しいかも

**Comment by kasumi0** [comment]
つけるなら下層画面にだけですか？Homeにもつけますか？
Homeはせっかく100vh完結のデザインだからつけるのは野暮な気もします。
一般的なコンテンツは、サイト名(ロゴなど)、連絡先(所在地、telなど)、グロナビ(headerよりも下層の全てのページが常に表示されているサイトマップ的なもの)、SNSナビ、copyrightなどですが、その中から取捨選択すればいいかと思います。またポートフォリオならユニークなお礼メッセージもあってもおもしろいかもー！

**Comment by ShionTerunaga** [comment]
@kasumi0 
> つけるなら下層画面にだけですか？Homeにもつけますか？

Homeねー
迷ってます。

> Homeはせっかく100vh完結のデザインだからつけるのは野暮な気もします。
一般的なコンテンツは、サイト名(ロゴなど)、連絡先(所在地、telなど)、グロナビ(headerよりも下層の全てのページが常に表示されているサイトマップ的なもの)、SNSナビ、copyrightなどですが、その中から取捨選択すればいいかと思います。

なるほどです。
つけなくても良い気はしますね。

> またポートフォリオならユニークなお礼メッセージもあってもおもしろいかもー！

確かに！
その辺を話し合いましょう！！！！

**Comment by kasumi0** [comment]
Homeは全体のナビ機能のみであることと、SNSナビもあるので、つけるならサイン的な感じでcopyrightをさりげなく下に入れておく程度がいい気がします！
下層ページのfooterのコンテンツに関してはご検討ください！

**Comment by ShionTerunaga** [comment]
footerはいいかな〜
