### ISSUE TITLE
「このサイトを作成するにあたって」というページを追加

### ISSUE THREAD

**Issue by ShionTerunaga** [ShionTerunaga/new-site-2024#26]
# 内容

今回、自分一人でサイトを作ったわけではない。
自分のサイトだがこのデザインはかすみさんが考えたものなので記載と共に私からのお礼・紹介を載せたい

# 相談事項

- デザイン
- 記載内容
- githubは載せておきたいな
- 近い将来かすみさんのサイトのリンクを貼る(いつ完成するだろうね🤪)

**Comment by kasumi0** [comment]
光栄です🥺
ページのコンテンツについては、使っている技術スタック、こだわりポイントなどのセクションもあるとアピールにもなるし充実した内容になるかなと思いました！でthnksセクションは一番下にこっそりと、、

**Comment by ShionTerunaga** [comment]
一旦コンテンツを作成する。
スタイルはその後。
