### ISSUE TITLE
Activityページのデザインも検討したい

### ISSUE THREAD

**Issue by ShionTerunaga** [ShionTerunaga/new-site-2024#29]
# 内容

<img width="1093" alt="スクリーンショット 2024-10-11 5 26 22" src="https://github.com/user-attachments/assets/83c142c7-a902-4355-9559-814f846a8e31">

introductionのページは上記のように変更したのでそれに基づいてアクティビティの部分も同じように変更したい。

<img width="1261" alt="スクリーンショット 2024-10-11 5 29 22" src="https://github.com/user-attachments/assets/5e519913-42eb-45c6-a1ab-9704cfb24063">

詳細コンテンツの方は後ほど

**Comment by ShionTerunaga** [comment]
@kasumi0 
デザイン提案に協力をお願いしたいです。

**Comment by kasumi0** [comment]
ここは背景色と文字色を合わせるだけで、レイアウトはこのままでもいいと思います。
私が１からデザインするなら画像のような感じで
icon Title
Description
みたいなカードレイアウトにすると思います。画像はvercelのUIです。iconは今使われているアイコンライブラリからTitleっぽいのを引っ張ってくるかsvg拾って来るかすると思います。
ご検討ください。よろしくお願いします！

<img width="958" alt="スクリーンショット 2024-10-12 0 07 23" src="https://github.com/user-attachments/assets/fd15bfc1-4c49-4e24-b67c-52b7fc31c894">

**Comment by ShionTerunaga** [comment]
@kasumi0 
連絡遅くなって申し訳ないです。
上記のカードの形にするなら他のページで使われるカードに統一した方がいいかな〜って思います。
